name: ci-push
on: [push]
jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: format code
        run: scripts/format_code.sh
      - name: check diff
        run: .github/format_check_diff.sh
  linux-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: init
        run: sudo apt update -yqq; sudo apt install -yqq ninja-build xorg-dev libwayland-dev libxkbcommon-dev wayland-protocols extra-cmake-modules
      - name: configure
        run: export CC=gcc-14; export CXX=g++-14; cmake -S . --preset=default -B build -DKVF_USE_FREETYPE=OFF
      - name: build debug
        run: cmake --build build --config=Debug
      - name: build release
        run: cmake --build build --config=Release
  linux-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: init
        run: sudo apt update -yqq; sudo apt install -yqq ninja-build xorg-dev libwayland-dev libxkbcommon-dev wayland-protocols extra-cmake-modules
      - name: configure
        run: cmake -S . --preset=ninja-clang -B build -DKVF_USE_FREETYPE=OFF
      - name: build debug
        run: cmake --build build --config=Debug
      - name: build release
        run: cmake --build build --config=Release
  windows-vs22:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: configure
        run: cmake -S . --preset=vs22 -B build -DKVF_USE_FREETYPE=OFF
      - name: build debug
        run: cmake --build build --config=Debug
      - name: build release
        run: cmake --build build --config=Release
  windows-clang:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: init
        run: choco install ninja
      - name: configure
        run: cmake -S . --preset=ninja-clang -B build -DKVF_USE_FREETYPE=OFF
      - name: build debug
        run: cmake --build build --config=Debug
      - name: build release
        run: cmake --build build --config=Release
